project 'HelloRest/HelloRest.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

pod 'SwiftyJSON'
pod 'Alamofire'

target 'HelloRest' do

end

target 'HelloRestSpecs' do
  pod 'Quick', '>= 0.10'
  pod 'Nimble', '>= 5.0'
  pod 'OHHTTPStubs'
  pod 'OHHTTPStubs/Swift'
end
